spring.application.name=CornCinema

spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_corn
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.show_sql=true

spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.web.resources.cache.cachecontrol.no-cache=true
spring.mvc.hiddenmethod.filter.enabled=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

